name: .NET CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # https://endoflife.date/dotnet
        dotnet-version: [6, 7, 8]

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage"
      - name: Upload coverage to Codecov
        if: ${{ matrix.dotnet-version == '8' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
